name: Trigger auto deployment for acahandson

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/acahandson-AutoDeployTrigger-dadb14ff-97fc-4a7d-bfc7-14f5e21777ba.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAHANDSON_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.ACAHANDSON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAHANDSON_REGISTRY_PASSWORD }}
          containerAppName: acahandson
          resourceGroup: handsonRG
          imageToBuild: saiut/nginx-js:${{ github.sha }}
          
            

     

